#ifndef MODERN_SQLITE_TESTS_COMPATIBILITY_BTREE_WRITER_CRASH_COMPATIBILITY_HPP_
#define MODERN_SQLITE_TESTS_COMPATIBILITY_BTREE_WRITER_CRASH_COMPATIBILITY_HPP_

namespace modern_sqlite::test {

void RunBtreeWriterCrashCompatibility();

}  // namespace modern_sqlite::test

#endif  // MODERN_SQLITE_TESTS_COMPATIBILITY_BTREE_WRITER_CRASH_COMPATIBILITY_HPP_
